### ISSUE TITLE
余白には前月/次月の日付表示を行わない件について

### ISSUE THREAD

**Issue by TakamasaSugiura** [swatanabe214/study_marking_201511#10]
インスペクション会のめもに

```
・週の途中で最初/最後の日付を迎えた場合の余白には前月/次月の日付表示を行わない。
```

とありますが、
前月/次月の日付が表示されています。
![pic002](https://cloud.githubusercontent.com/assets/7827645/12700848/f51fc4ea-c836-11e5-85d0-4ebdaa1d22c0.png)

**Comment by swatanabe214** [comment]
今回使用したプラグイン(fullcalendar)では当月以外の日付を削除することができなかったため
暫定的に当月以外の日付をグレーアウトしました。
fullcalendarを使用しない実装を検討させてください。
ゼロからの実装となるので時間がかかりそうです…

**Comment by TakamasaSugiura** [comment]
当月以外の日付が確かに見えなくなっていますが、
実際には日付が出力されていますのでＮＧです。(Ctrl + aで表示される。)
当月以外の日付はそもそも出力しないようにしましょう。

fullcallendar.jsの5020行目あたりから始まる
renderDayRowHtml関数からたどっていくと、renderNumberCellHtml関数(5083行目から)内で日付をセットしているところがあります。
そこで、date.month()などで、今月かどうか判定して処理分岐をすればいいのではないでしょうか？

@60f3cb3

**Comment by TakamasaSugiura** [comment]
確認しました。
@1ea8ceb
