### ISSUE TITLE
予定の表示について

### ISSUE THREAD

**Issue by TakamasaSugiura** [swatanabe214/study_marking_201511#9]
予定の先頭に「12a」と出ていますが、これは何を意味するのでしょうか？
![pic003](https://cloud.githubusercontent.com/assets/7827645/12700821/c5002ae4-c835-11e5-857d-0dbd67f11bf9.png)

**Comment by swatanabe214** [comment]
今回の課題ではスケジュールに時刻を指定していないため、時刻の初期値が設定されている状態です。

**Comment by TakamasaSugiura** [comment]
なるほど。12aは「午前12時(12 am)」を意味するのでしょうか？
ただ、今回の課題では使い道がなく、説明を受けないと「？？？」となってしまいますので、
「12a」は消してしまいましょう。

@47fec0f

**Comment by TakamasaSugiura** [comment]
確認しました。
@e8ec3c5
